version: "3.5"

services:
  api-service:
    build:
      context: ./apiService/
      dockerfile: Dockerfile
    working_dir: /serverHome
    volumes:
      - ./apiService:/serverHome
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always
  indexer-service:
      build:
        context: ./indexerService
        dockerfile: Dockerfile
      working_dir: /serverHome
      volumes:
        - ./indexerService:/serverHome
      depends_on:
        - db
      entrypoint: go run main.go
      restart: always
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #   - ./initSchema:/docker-entrypoint-initdb.d
    restart: always